apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.database.password | b64enc | quote }} # Base64 encoded password

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-jwt-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  secretKey: {{ .Values.jwt.secretKey | b64enc | quote }} # Base64 encoded JWT secret key
